AWSTemplateFormatVersion: '2010-09-09'
Outputs:
  LatestAMI:
    Description: Latest AMI
    Export:
      Name: !Sub '${AWS::StackName}-LatestAMI'
    Value: !GetAtt 'AMIInfo.LatestADCAMI'
  LatestAMILambdaRole:
    Description: ''
    Export:
      Name: !Sub '${AWS::StackName}-LatestAMILambdaRole'
    Value: !Sub 'https://console.aws.amazon.com/iam/home#/roles/${LatestAMILambdaRole}'
Parameters:
  ADCProductName:
    AllowedValues:
      - Citrix ADC VPX - Customer Licensed
      - Citrix ADC VPX Express - 20 Mbps
      - Citrix ADC VPX Standard Edition - 10 Mbps
      - Citrix ADC VPX Standard Edition - 200 Mbps
      - Citrix ADC VPX Standard Edition - 1000 Mbps
      - Citrix ADC VPX Standard Edition - 3Gbps
      - Citrix ADC VPX Standard Edition - 5Gbps
      - Citrix ADC VPX Premium Edition - 10 Mbps
      - Citrix ADC VPX Premium Edition - 200 Mbps
      - Citrix ADC VPX Premium Edition - 1000 Mbps
      - Citrix ADC VPX Premium Edition - 3Gbps
      - Citrix ADC VPX Premium Edition - 5Gbps
      - Citrix ADC VPX Advanced Edition - 10 Mbps
      - Citrix ADC VPX Advanced Edition - 200 Mbps
      - Citrix ADC VPX Advanced Edition - 1000 Mbps
      - Citrix ADC VPX Advanced Edition - 3Gbps
      - Citrix ADC VPX Advanced Edition - 5Gbps
    Default: Citrix ADC VPX - Customer Licensed
    Description: ''
    Type: String
  ADCProductVersion:
    AllowedValues:
      - '13.0'
    Default: '13.0'
    Description: ''
    Type: String
  S3BucketName:
    AllowedPattern: ()|^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    Description: ''
    Type: String
  S3Key:
    Description: ''
    Type: String
Resources:
  AMIInfo:
    Properties:
      ADCProduct: !Ref 'ADCProductName'
      ADCVersion: !Ref 'ADCProductVersion'
      ServiceToken: !GetAtt 'AMIInfoFunction.Arn'
    Type: AWS::CloudFormation::CustomResource
  AMIInfoFunction:
    Properties:
      Code:
        S3Bucket: !Ref 'S3BucketName'
        S3Key: !Ref 'S3Key'
      Description: AMIInfoFunction
      Handler: lambda_get_latest_citrixadc_ami.lambda_handler
      Role: !GetAtt 'LatestAMILambdaRole.Arn'
      Runtime: python3.6
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-AMIInfoFunction'
      Timeout: 30
    Type: AWS::Lambda::Function
  LatestAMILambdaRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: '2012-10-17'
      Description: ''
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - ec2:DescribeImages
                Effect: Allow
                Resource: '*'
            Version: '2012-10-17'
          PolicyName: GetVPCCIDR
    Type: AWS::IAM::Role
